# Import Bibliotheken

In [1]:
# Festlegung des Device
import platform

# Laden der Daten
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# Operationen mit Texten
import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
import spacy

# Modell
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim

# Evaluierung
import torchmetrics

# Auswertung der Evaluation
import pandas as pd
import altair as alt
import numpy as np

from sklearn import preprocessing

### Package Versionen

In [2]:
for package in [torchtext,torch, torchmetrics, spacy, alt, pd]:
    print(f'{package.__name__}: {package.__version__}')

torchtext: 0.13.1
torch: 1.12.1
torchmetrics: 0.9.3
spacy: 3.4.2
altair: 4.2.0
pandas: 1.4.3


# Device Auswahl

In [3]:
device = torch.device(
    "cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

# Daten

## Dataset

### Erstellung Dataset

In [4]:
comment_df = pd.read_excel('data/clean/Google_Rezensionen.xlsx')
comment_df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

In [5]:
class TeamGoogleBewertungenDataSet(Dataset):

    def __init__(self, data):
        self.data = data
    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        text = comment_df.iloc[index]['Kommentar']
        category = comment_df.iloc[index]['Kategorien']
        return text, category

### Bestimmung Test- und Traningsdaten

In [6]:
# Bestimmung der Länge der Test- und Traningsdaten
dataset = TeamGoogleBewertungenDataSet(comment_df)
len_train = round(len(dataset)* 0.7)
len_test = round(len(dataset) * 0.3)
assert len(comment_df) == len_train + len_test

In [7]:
# Zufällige Aufsplittung der Anzahl von Test- und Trainingsdaten
train_set, test_set = torch.utils.data.random_split(dataset, [len_train, len_test]) 

In [8]:
len(train_set)

2798

In [9]:

len(test_set)

1199

In [10]:
# next(iter(train_set))

## Dataloader

### Tokenisierung

In [11]:
tokenizer = get_tokenizer(
    'spacy', 
    language='de_core_news_lg')

In [12]:
# Beispiel für Anwendung des tokenizer
# sentence = "This isn't a very long example."
# tokenizer(sentence)

### Erstellung Vokabular

In [13]:
def yield_tokens(data_iter):
    for text, _ in data_iter:
        yield tokenizer(text)

In [14]:
# Länge des Trainungsets
len(train_set)

2798

In [15]:
tokens = yield_tokens(train_set)

In [16]:
next(iter(tokens))

['haben', 'luftpumpe']

In [17]:
vocab = build_vocab_from_iterator(tokens, min_freq=2, specials=["<unk>"])

vocab.set_default_index(vocab["<unk>"])

In [18]:
len(vocab)

2455

In [19]:
vocab(['Hallo', 'sehr', 'Personal'])

[0, 4, 0]

In [20]:
vocab.lookup_token(0)

'<unk>'

### Encoding

In [21]:
onehot = torch.zeros(1,len(vocab))

In [22]:
pos = vocab(['nette', 'Bedienung', 'sauber'])
pos

[31, 0, 49]

In [23]:
def encode(text, vocab):
    tokens = tokenizer(text)
    onehot = torch.zeros(1,len(vocab))
    onehot[:,vocab(tokens)] = 1
    return onehot

### Multilabel Encoding

In [24]:
import torch
import torch.nn

In [25]:
df = comment_df.explode('Kategorien')
df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

#### Kategorien splitten

In [26]:
einzelLabels = comment_df['Kategorien'].str.split(',')
label_list_export = einzelLabels.to_list()
label_list_export

[['Personal', 'Shop', 'Bistro'],
 ['Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal'],
 ['Pricing', 'DigitalFueling'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing', 'Kraftstoffauswahl'],
 ['Personal', 'Öffnungszeiten'],
 ['Personal', 'SB-Waschboxen', 'Waschanlage'],
 ['Shop'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing'],
 ['Bistro'],
 ['Personal', 'Pricing', 'Shop', 'Waschanlage'],
 ['Personal'],
 ['Personal'],
 ['Bistro'],
 ['Erscheinungsbild'],
 ['Personal', 'Pricing'],
 ['Personal'],
 ['Personal'],
 ['Personal', 'Shop'],
 ['Erscheinungsbild'],
 ['Personal', 'Bistro'],
 ['Erscheinungsbild', 'Nacht-/Tankautomat', 'Waschanlage', 'Staubsauger'],
 ['Pricing'],
 ['Personal'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal'],
 ['Bistro'],
 ['Pricing', 'Kraftstoffauswahl'],
 ['Pricing'],
 ['Nacht-/Tankautomat'],
 ['Shop', 'Bistro'],
 ['Erscheinungsbild', 'Personal', 'Sanitär

##### In der nachfolgenden Zelle wird aus der verschachtelten Liste eine "flache Liste"

In [27]:
flat_list = []
for sublist in label_list_export:
    for item in sublist:
        flat_list.append(item)

flat_list

['Personal',
 'Shop',
 'Bistro',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'DigitalFueling',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Kraftstoffauswahl',
 'Personal',
 'Öffnungszeiten',
 'Personal',
 'SB-Waschboxen',
 'Waschanlage',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Bistro',
 'Personal',
 'Pricing',
 'Shop',
 'Waschanlage',
 'Personal',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Pricing',
 'Personal',
 'Personal',
 'Personal',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Nacht-/Tankautomat',
 'Waschanlage',
 'Staubsauger',
 'Pricing',
 'Personal',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Bistro',
 'Pricing',
 'Kraftstoffauswahl',
 'Pricing',
 'Nacht-/Tankautomat',
 'Shop',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Sanitär',
 'Bistro',
 'Pricing',
 'Verkehrsanbindung'

### Grafische Darstellung von der Anzahl der Kategorien

In [28]:
count_list = ([ [l, flat_list.count(l)] for l in set(flat_list)])
count_list

[['Nacht-/Tankautomat', 95],
 ['Luft', 86],
 ['Pricing', 1000],
 ['Kraftstoffauswahl', 280],
 ['Bistro', 716],
 ['Sanitär', 138],
 ['Staubsauger', 32],
 ['Verkehrsanbindung', 111],
 ['Zapfsäulen', 45],
 ['WLAN', 3],
 ['Paketservice', 32],
 ['DigitalFueling', 30],
 ['E-Mobilität', 7],
 ['Waschanlage', 462],
 ['Personal', 2790],
 ['Tankpool', 3],
 ['SB-Waschboxen', 45],
 ['Shop', 554],
 ['AdBlue', 37],
 ['E-Fuels', 1],
 ['Erscheinungsbild', 534],
 ['Öffnungszeiten', 129],
 ['Werkstatt', 45],
 ['Kartenakzeptanzen', 145]]

In [29]:
count_df = pd.DataFrame(count_list)
count_df.columns= ['Kategorie', 'Anzahl']
count_df

Kategorie  Anzahl
0   Nacht-/Tankautomat      95
1                 Luft      86
2              Pricing    1000
3    Kraftstoffauswahl     280
4               Bistro     716
5              Sanitär     138
6          Staubsauger      32
7    Verkehrsanbindung     111
8           Zapfsäulen      45
9                 WLAN       3
10        Paketservice      32
11      DigitalFueling      30
12         E-Mobilität       7
13         Waschanlage     462
14            Personal    2790
15            Tankpool       3
16       SB-Waschboxen      45
17                Shop     554
18              AdBlue      37
19             E-Fuels       1
20    Erscheinungsbild     534
21      Öffnungszeiten     129
22           Werkstatt      45
23   Kartenakzeptanzen     145

In [30]:
kategorien_anzahl_bar = alt.Chart(count_df).mark_bar(color='#EC6500').encode(
    x = alt.X('Anzahl', title='Anzahl Vorkomnisse'),
    y = alt.Y('Kategorie', title='Kategorie', sort='-x')
).properties(
    title='Kategorieklassen'
)
kategorien_anzahl_text = kategorien_anzahl_bar.mark_text(
    align='left',
    baseline= 'middle',
    dx=3
).encode(
    text='Anzahl:Q'
)

kategorien_anzahl_chart = (kategorien_anzahl_bar + kategorien_anzahl_text)
kategorien_anzahl_chart.properties(width=550)

alt.LayerChart(...)

##### Doppelte Werte werden entfernt, so dass jeder Eintrag nur einmalig vorhanden ist. Dies erreichen wir mit set()

In [31]:
flat_set = set(flat_list)
flat_set

{'AdBlue',
 'Bistro',
 'DigitalFueling',
 'E-Fuels',
 'E-Mobilität',
 'Erscheinungsbild',
 'Kartenakzeptanzen',
 'Kraftstoffauswahl',
 'Luft',
 'Nacht-/Tankautomat',
 'Paketservice',
 'Personal',
 'Pricing',
 'SB-Waschboxen',
 'Sanitär',
 'Shop',
 'Staubsauger',
 'Tankpool',
 'Verkehrsanbindung',
 'WLAN',
 'Waschanlage',
 'Werkstatt',
 'Zapfsäulen',
 'Öffnungszeiten'}

In [32]:
unflat = [[x] for x in flat_set]

In [33]:
label_vocab = build_vocab_from_iterator(unflat, min_freq=1, specials=["<unk>"])

label_vocab.set_default_index(vocab["<unk>"])

In [34]:
label_vocab.lookup_token(3)

'DigitalFueling'

#### Dictionary erstellen

In [35]:
label_dict = {label:i for i, label in enumerate(flat_set)}
label_dict

{'Nacht-/Tankautomat': 0,
 'Luft': 1,
 'Pricing': 2,
 'Kraftstoffauswahl': 3,
 'Bistro': 4,
 'Sanitär': 5,
 'Staubsauger': 6,
 'Verkehrsanbindung': 7,
 'Zapfsäulen': 8,
 'WLAN': 9,
 'Paketservice': 10,
 'DigitalFueling': 11,
 'E-Mobilität': 12,
 'Waschanlage': 13,
 'Personal': 14,
 'Tankpool': 15,
 'SB-Waschboxen': 16,
 'Shop': 17,
 'AdBlue': 18,
 'E-Fuels': 19,
 'Erscheinungsbild': 20,
 'Öffnungszeiten': 21,
 'Werkstatt': 22,
 'Kartenakzeptanzen': 23}

#### Tensor

In [36]:
doc2 = label_list_export[2]
doc2

['Personal', 'Waschanlage']

In [37]:
pos_vals = [label_dict[val] for val in doc2]
pos_vals

[14, 13]

In [38]:
labels = torch.LongTensor(pos_vals)
labels

tensor([14, 13])

In [39]:
y_onehot = nn.functional.one_hot(labels, num_classes=24)
y_onehot

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
y_onehot = y_onehot.sum(dim=0).float()
y_onehot

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])

In [41]:
# labels = torch.tensor([1,5,8,0])
# labels = labels.unsqueeze(0)
# target = torch.zeros(labels.size(0), 24).scatter_(1, labels, 1.)
# print(target)

### Erstellung Dataloader

In [42]:
# label_pipeline = lambda x: int(x) -1

In [43]:
def collate_batch(batch):
    label_list, text_list = [], []
 
    for (_text,_label) in batch:
    
        # Vorverarbeitung der Label
        # label_list.append(label_pipeline(_label))
        processed_labels = encode(_label, label_vocab)

        label_list.append(processed_labels)

        # Vorverarbeitung der Texte
        processed_text = encode(_text, vocab)
        
        # Zusammenführen sämtlicher Textrepräsentationen in einer Liste
        text_list.append(processed_text)
 
    # Zusammenführen aller Label in einem Tensor
    labels = torch.cat(label_list, dim=0)
    
    # Verbinden der Tensoren in text_list zu einem Tensor
    texts = torch.cat(text_list, dim = 0)

    # Ausgabe der Texte und der Label
    return texts.to(device), labels.to(device)

In [44]:
train_loader = DataLoader(
 train_set, batch_size=64,
 shuffle=True,
 collate_fn=collate_batch,
 num_workers=0
)

## Architektur und Training

### Architektur

In [45]:
class LinearTextClassificationModel(nn.Module):

    def __init__(self, vocab_size, num_class):
        super(LinearTextClassificationModel, self).__init__()
        self.fc1 = nn.Linear(vocab_size, 200)
        self.fc2 = nn.Linear(200, num_class)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        output = F.softmax(x, dim=1)
        return output

In [46]:
vocab_size = len(vocab)
num_class = 25
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

### Training

In [47]:
# Hyperparameter

## Festlegung Lernrate
learning_rate = 0.05

## Initialisierung Fehlerfunktion
loss_fn = nn.BCEWithLogitsLoss()

## Initialisierung Optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate, momentum=0.9)

## Definition der Epochen
num_epochs = 50

In [48]:
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)

loss_hist = {}
accuracy_hist = {}

In [49]:
for (text, label) in train_loader:
    #print(label[[0][0]])
    #print(text)
    labelnew = label.type(torch.LongTensor)
    print(labelnew[[0][0]])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,


In [50]:
# Training
model.train()

for epoch in range(num_epochs):

    # Dokumentation Loss -> Erkennung ob Netz konvergiert
    running_loss = 0.0
    num_batches = 0

    for (text, label) in train_loader:
        num_batches += 1
        pred = model(text)

        # Der Fehler wird berechnet
        loss = loss_fn(pred, label)
        # Der Fehler wird über das Netz zurückpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        ## Bestimmung der Accuracy für den Batch
        train_accuracy(pred, label.type(torch.LongTensor))
        
        # running loss
        running_loss +=loss.item()
 
    loss_hist[epoch] = running_loss/num_batches
 
    batch_train_accuracy = train_accuracy.compute()
    print(f"Training Accuracy for epoch {epoch}:{batch_train_accuracy}")
    accuracy_hist[epoch] = batch_train_accuracy.cpu().item()
    train_accuracy.reset()

Training Accuracy for epoch 0:0.0
Training Accuracy for epoch 1:0.0
Training Accuracy for epoch 2:0.0
Training Accuracy for epoch 3:0.0
Training Accuracy for epoch 4:0.0
Training Accuracy for epoch 5:0.0
Training Accuracy for epoch 6:0.0
Training Accuracy for epoch 7:0.0
Training Accuracy for epoch 8:0.0
Training Accuracy for epoch 9:0.0
Training Accuracy for epoch 10:0.0
Training Accuracy for epoch 11:0.0
Training Accuracy for epoch 12:0.0
Training Accuracy for epoch 13:0.0
Training Accuracy for epoch 14:0.0
Training Accuracy for epoch 15:0.0
Training Accuracy for epoch 16:0.0
Training Accuracy for epoch 17:0.0
Training Accuracy for epoch 18:0.0
Training Accuracy for epoch 19:0.0
Training Accuracy for epoch 20:0.0
Training Accuracy for epoch 21:0.0
Training Accuracy for epoch 22:0.0
Training Accuracy for epoch 23:0.0
Training Accuracy for epoch 24:0.0017869906732812524
Training Accuracy for epoch 25:0.012508935295045376
Training Accuracy for epoch 26:0.05360972136259079
Training Accur

### Auswertung Fehlerentwicklung

In [51]:
loss_df = pd.DataFrame.from_dict(loss_hist, orient= 'index').reset_index()

loss_df.columns = ['Epoch', 'Loss']
loss_df.head()

Epoch      Loss
0      0  0.709623
1      1  0.709575
2      2  0.709522
3      3  0.709468
4      4  0.709411

In [52]:
train_chart = alt.Chart(loss_df).mark_line().encode(
    x=alt.X('Epoch', title = 'Anzahl Epochen'),
    y=alt.Y('Loss', title = 'Mittlerer Fehler')
)
# glue('train-loss-team', train_chart,display=True)
train_chart

alt.Chart(...)

### Auswertung Genauigkeit

In [53]:
accuracy_df = pd.DataFrame.from_dict(accuracy_hist, orient = 'index').reset_index()
accuracy_df.columns = ['Epoch', 'Accuracy']
accuracy_df.head()

Epoch  Accuracy
0      0       0.0
1      1       0.0
2      2       0.0
3      3       0.0
4      4       0.0

In [54]:
accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
    x=alt.X('Epoch',title = 'Anzahl Epochen'),
    y=alt.Y('Accuracy', title = 'Genauigkeit')
)
accuracy_chart

alt.Chart(...)

## Evaluierung

In [55]:
model.eval()

LinearTextClassificationModel(
  (fc1): Linear(in_features=2455, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=25, bias=True)
)

### Gesamtevaluierung

In [56]:
test_loader = DataLoader(test_set, batch_size= 64, shuffle=True,collate_fn=collate_batch)

In [57]:
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)

with torch.no_grad():
    for (text, label) in test_loader:
        # Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()

In [58]:
total_valid_accuracy

tensor(0.3303)

### Evaluierung nach Klassen

In [59]:
# Evaluieren
valid_accuracy = torchmetrics.Accuracy(
    average=None,
    num_classes=25
).to(device)

with torch.no_grad():
    for(text, label) in test_loader:
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()
    total_valid_accuracy

In [60]:
total_valid_accuracy

tensor([0.5179, 0.9950, 0.8265, 0.9950,    nan, 0.9983, 0.8649, 0.9608, 0.9366,
        0.9825, 0.9758, 0.9942, 0.7048, 0.7473, 0.9900, 0.9725, 0.8616, 0.9950,
        0.9992, 0.9716,    nan, 0.8924, 0.9917, 0.9908, 0.9650])

### Evaluierung nach der Anzahl der Epochen

In [61]:
train_loader = DataLoader(train_set, batch_size=64, shuffle=True, collate_fn=collate_batch)

In [62]:
test_loader = DataLoader(test_set, batch_size=64, shuffle=True, collate_fn=collate_batch)

In [63]:
vocab_size = len(vocab)
num_class = 25
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

In [64]:
learning_rate = 0.05

loss_fn = nn.BCEWithLogitsLoss()

optimizer = optim.SGD(model.parameters(),lr=learning_rate,momentum=0.9)

num_epochs = 50

In [65]:
# Evaluierung wurd vorbereitet
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)

train_accuracy_hist = {}
train_loss_hist = {}

valid_accuracy_hist = {}
valid_loss_hist = {}

In [66]:
for epoch in range(num_epochs):

    # Loss wird dokumentiert, sodass zu erkenne ist, ob das Netz konvergiert
    num_train_batches = 0
    num_eval_batches = 0
    train_running_loss = 0.0
    eval_running_loss = 0.0

    model.train()
    for (text, label) in train_loader:
        num_train_batches += 1
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        # Der Fehler wird berechnet
        # Als Ausgabe wird ein Tensor zurückgegeben
        loss = loss_fn(pred, label)
        # Der Fehler wird über das Netz zurükpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        # Aktualisierung des States der train_accurracy
        train_accuracy.update(pred, label.type(torch.LongTensor))
        # running loss
        train_running_loss += loss.item()

    train_loss_hist[epoch] = train_running_loss / num_train_batches

    # Berechnung der Trainingsgenauigkeit für die Epoche
    total_train_accuracy = train_accuracy.compute()
    # Hinzufügen der Trainingsgenauigkeit zu dem Dictionary
    train_accuracy_hist[epoch] = total_train_accuracy.cpu().numpy()

    # Validierung
    model.eval()
    with torch.no_grad():
        for (text, label) in test_loader:
            num_eval_batches += 1
            # Die Vorhersage wird für das Model erzeugt
            pred = model(text)
            # Test loss
            eval_loss = loss_fn(pred, label)
            # Running loss
            eval_running_loss += eval_loss.item()
            # Aktualisierung des States der valid_accuracy
            valid_accuracy.update(pred, label.type(torch.LongTensor))
    
    valid_loss_hist[epoch] = eval_running_loss/num_eval_batches

    # Berechnung der Validierungsgenauigkeit für die Epoche
    total_valid_accuracy = valid_accuracy.compute()
    # Hinzufügen der Validierungsgenauigkeit zum Dictionary
    valid_accuracy_hist[epoch] = total_valid_accuracy.cpu().numpy()

    print(f"Training Accuracy for epoch {epoch}: {total_train_accuracy}")
    print(f"Validation Accuracy for epoch {epoch}: {total_valid_accuracy}")
    train_accuracy.reset()
    valid_accuracy.reset()

Training Accuracy for epoch 0: 0.0
Validation Accuracy for epoch 0: 0.0
Training Accuracy for epoch 1: 0.0
Validation Accuracy for epoch 1: 0.0
Training Accuracy for epoch 2: 0.0
Validation Accuracy for epoch 2: 0.0
Training Accuracy for epoch 3: 0.0
Validation Accuracy for epoch 3: 0.0
Training Accuracy for epoch 4: 0.0
Validation Accuracy for epoch 4: 0.0
Training Accuracy for epoch 5: 0.0
Validation Accuracy for epoch 5: 0.0
Training Accuracy for epoch 6: 0.0
Validation Accuracy for epoch 6: 0.0
Training Accuracy for epoch 7: 0.0
Validation Accuracy for epoch 7: 0.0
Training Accuracy for epoch 8: 0.0
Validation Accuracy for epoch 8: 0.0
Training Accuracy for epoch 9: 0.0
Validation Accuracy for epoch 9: 0.0
Training Accuracy for epoch 10: 0.0
Validation Accuracy for epoch 10: 0.0
Training Accuracy for epoch 11: 0.0
Validation Accuracy for epoch 11: 0.0
Training Accuracy for epoch 12: 0.0
Validation Accuracy for epoch 12: 0.0
Training Accuracy for epoch 13: 0.0
Validation Accuracy fo

In [67]:
train_loss_df = pd.DataFrame.from_dict(train_loss_hist, orient = "index").reset_index()
train_loss_df["type"] = "Train"
valid_loss_df = pd.DataFrame.from_dict(valid_loss_hist, orient = "index").reset_index()
valid_loss_df["type"] = "Test"
loss_df = pd.concat([train_loss_df,valid_loss_df])
loss_df.columns = ["Epoch", "Loss", "Type"]

In [68]:
train_eval_loss_chart = alt.Chart(loss_df).mark_line().encode(
    x = alt.X('Epoch', title='Anzahl Epochen'),
    y = alt.Y('Loss',title='Mittlerer Fehler'),
    color = alt.Color('Type',title='Typ')
)
train_eval_loss_chart

alt.Chart(...)

In [69]:
valid_accuracy_hist

{0: array(0., dtype=float32),
 1: array(0., dtype=float32),
 2: array(0., dtype=float32),
 3: array(0., dtype=float32),
 4: array(0., dtype=float32),
 5: array(0., dtype=float32),
 6: array(0., dtype=float32),
 7: array(0., dtype=float32),
 8: array(0., dtype=float32),
 9: array(0., dtype=float32),
 10: array(0., dtype=float32),
 11: array(0., dtype=float32),
 12: array(0., dtype=float32),
 13: array(0., dtype=float32),
 14: array(0., dtype=float32),
 15: array(0., dtype=float32),
 16: array(0., dtype=float32),
 17: array(0., dtype=float32),
 18: array(0., dtype=float32),
 19: array(0., dtype=float32),
 20: array(0., dtype=float32),
 21: array(0., dtype=float32),
 22: array(0., dtype=float32),
 23: array(0., dtype=float32),
 24: array(0., dtype=float32),
 25: array(0.00250209, dtype=float32),
 26: array(0.02001668, dtype=float32),
 27: array(0.07589658, dtype=float32),
 28: array(0.16513762, dtype=float32),
 29: array(0.24770643, dtype=float32),
 30: array(0.28773978, dtype=float32),
 

In [70]:
train_accuracy_hist

{0: array(0., dtype=float32),
 1: array(0., dtype=float32),
 2: array(0., dtype=float32),
 3: array(0., dtype=float32),
 4: array(0., dtype=float32),
 5: array(0., dtype=float32),
 6: array(0., dtype=float32),
 7: array(0., dtype=float32),
 8: array(0., dtype=float32),
 9: array(0., dtype=float32),
 10: array(0., dtype=float32),
 11: array(0., dtype=float32),
 12: array(0., dtype=float32),
 13: array(0., dtype=float32),
 14: array(0., dtype=float32),
 15: array(0., dtype=float32),
 16: array(0., dtype=float32),
 17: array(0., dtype=float32),
 18: array(0., dtype=float32),
 19: array(0., dtype=float32),
 20: array(0., dtype=float32),
 21: array(0., dtype=float32),
 22: array(0., dtype=float32),
 23: array(0., dtype=float32),
 24: array(0., dtype=float32),
 25: array(0.00107219, dtype=float32),
 26: array(0.00714796, dtype=float32),
 27: array(0.03395282, dtype=float32),
 28: array(0.09792709, dtype=float32),
 29: array(0.18084346, dtype=float32),
 30: array(0.25411007, dtype=float32),
 

In [71]:
# Erste Epoche löschen, da diese nicht neu initialisiert wird und Daten aus vorherigen Schritten enthält

del train_accuracy_hist[0]
del valid_accuracy_hist[0]

In [72]:
train_accuracy_df = pd.DataFrame.from_dict(train_accuracy_hist, orient = "index").reset_index()
train_accuracy_df["type"] = "Train"
valid_accuracy_df = pd.DataFrame.from_dict(valid_accuracy_hist, orient = "index").reset_index()
valid_accuracy_df["type"] = "Test"
accuracy_df = pd.concat([train_accuracy_df,valid_accuracy_df])
accuracy_df.columns = ["Epoch", "Accuracy", "Type"]

In [73]:
accuracy_df

Epoch  Accuracy   Type
0       1  0.000000  Train
1       2  0.000000  Train
2       3  0.000000  Train
3       4  0.000000  Train
4       5  0.000000  Train
..    ...       ...    ...
44     45  0.330275   Test
45     46  0.330275   Test
46     47  0.330275   Test
47     48  0.330275   Test
48     49  0.330275   Test

[98 rows x 3 columns]

In [74]:
train_eval_accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
    x = alt.X('Epoch',title='Anzahl Epochen'),
    y = alt.Y('Accuracy',title='Genauigkeit'),
    color = alt.Color('Type',title='Typ')
)
train_eval_accuracy_chart

alt.Chart(...)