# Import Bibliotheken

In [307]:
# Festlegung des Device
import platform

# Laden der Daten
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# Operationen mit Texten
import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
import spacy

# Modell
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim

# Evaluierung
import torchmetrics

# Auswertung der Evaluation
import pandas as pd
import altair as alt
import numpy as np

from sklearn import preprocessing

### Package Versionen

In [308]:
for package in [torchtext,torch, torchmetrics, spacy, alt, pd]:
    print(f'{package.__name__}: {package.__version__}')

torchtext: 0.13.1
torch: 1.12.1
torchmetrics: 0.9.3
spacy: 3.4.2
altair: 4.2.0
pandas: 1.4.3


# Device Auswahl

In [309]:
device = torch.device(
    "cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

# Daten

## Dataset

### Erstellung Dataset

In [310]:
comment_df = pd.read_excel('data/clean/Google_Rezensionen.xlsx')
comment_df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

In [311]:
class TeamGoogleBewertungenDataSet(Dataset):

    def __init__(self, data):
        self.data = data
    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        text = comment_df.iloc[index]['Kommentar']
        category = comment_df.iloc[index]['Kategorien']
        return text, category

### Bestimmung Test- und Traningsdaten

In [312]:
# Bestimmung der Länge der Test- und Traningsdaten
dataset = TeamGoogleBewertungenDataSet(comment_df)
len_train = round(len(dataset)* 0.7)
len_test = round(len(dataset) * 0.3)
assert len(comment_df) == len_train + len_test

In [313]:
# Zufällige Aufsplittung der Anzahl von Test- und Trainingsdaten
train_set, test_set = torch.utils.data.random_split(dataset, [len_train, len_test]) 

In [314]:
# next(iter(train_set))

## Dataloader

### Tokenisierung

In [315]:
tokenizer = get_tokenizer(
    'spacy', 
    language='de_core_news_lg')

In [316]:
# Beispiel für Anwendung des tokenizer
# sentence = "This isn't a very long example."
# tokenizer(sentence)

### Erstellung Vokabular

In [317]:
def yield_tokens(data_iter):
    for text, _ in data_iter:
        yield tokenizer(text)

In [318]:
# Länge des Trainungsets
len(train_set)

2798

In [319]:
tokens = yield_tokens(train_set)

In [320]:
next(iter(tokens))

['sprit',
 'riecht',
 'merkwürdig',
 'verbrauch',
 'ist',
 'höher',
 'als',
 'z',
 'b',
 'shell',
 'laden',
 'sieht',
 'sehr',
 'traurig',
 'aus',
 'aktuelle',
 'paysafe',
 'oder',
 'sowas',
 'fehlanzeige',
 'bzw',
 'personal',
 'ist',
 'nicht',
 'geschult']

In [321]:
vocab = build_vocab_from_iterator(tokens, min_freq=2, specials=["<unk>"])

vocab.set_default_index(vocab["<unk>"])

In [322]:
len(vocab)

2397

In [323]:
vocab(['Hallo', 'sehr', 'Personal'])

[0, 4, 0]

In [324]:
vocab.lookup_token(0)

'<unk>'

### Encoding

In [325]:
onehot = torch.zeros(1,len(vocab))

In [326]:
pos = vocab(['nette', 'Bedienung', 'sauber'])
pos

[29, 0, 46]

In [327]:
def encode(text, vocab):
    tokens = tokenizer(text)
    onehot = torch.zeros(1,len(vocab))
    onehot[:,vocab(tokens)] = 1
    return onehot

### Multilabel Encoding

In [328]:
import torch
import torch.nn

In [329]:
df = comment_df.explode('Kategorien')
df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

#### Kategorien splitten

In [330]:
einzelLabels = comment_df['Kategorien'].str.split(',')
label_list_export = einzelLabels.to_list()
label_list_export

[['Personal', 'Shop', 'Bistro'],
 ['Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal'],
 ['Pricing', 'DigitalFueling'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing', 'Kraftstoffauswahl'],
 ['Personal', 'Öffnungszeiten'],
 ['Personal', 'SB-Waschboxen', 'Waschanlage'],
 ['Shop'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing'],
 ['Bistro'],
 ['Personal', 'Pricing', 'Shop', 'Waschanlage'],
 ['Personal'],
 ['Personal'],
 ['Bistro'],
 ['Erscheinungsbild'],
 ['Personal', 'Pricing'],
 ['Personal'],
 ['Personal'],
 ['Personal', 'Shop'],
 ['Erscheinungsbild'],
 ['Personal', 'Bistro'],
 ['Erscheinungsbild', 'Nacht-/Tankautomat', 'Waschanlage', 'Staubsauger'],
 ['Pricing'],
 ['Personal'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal'],
 ['Bistro'],
 ['Pricing', 'Kraftstoffauswahl'],
 ['Pricing'],
 ['Nacht-/Tankautomat'],
 ['Shop', 'Bistro'],
 ['Erscheinungsbild', 'Personal', 'Sanitär

##### In der nachfolgenden Zelle wird aus der verschachtelten Liste eine "flache Liste"

In [331]:
flat_list = []
for sublist in label_list_export:
    for item in sublist:
        flat_list.append(item)

flat_list

['Personal',
 'Shop',
 'Bistro',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'DigitalFueling',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Kraftstoffauswahl',
 'Personal',
 'Öffnungszeiten',
 'Personal',
 'SB-Waschboxen',
 'Waschanlage',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Bistro',
 'Personal',
 'Pricing',
 'Shop',
 'Waschanlage',
 'Personal',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Pricing',
 'Personal',
 'Personal',
 'Personal',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Nacht-/Tankautomat',
 'Waschanlage',
 'Staubsauger',
 'Pricing',
 'Personal',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Bistro',
 'Pricing',
 'Kraftstoffauswahl',
 'Pricing',
 'Nacht-/Tankautomat',
 'Shop',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Sanitär',
 'Bistro',
 'Pricing',
 'Verkehrsanbindung'

##### Doppelte Werte werden entfernt, so dass jeder Eintrag nur einmalig vorhanden ist. Dies erreichen wir mit set()

In [332]:
flat_set = set(flat_list)
flat_set

{'AdBlue',
 'Bistro',
 'DigitalFueling',
 'E-Fuels',
 'E-Mobilität',
 'Erscheinungsbild',
 'Kartenakzeptanzen',
 'Kraftstoffauswahl',
 'Luft',
 'Nacht-/Tankautomat',
 'Paketservice',
 'Personal',
 'Pricing',
 'SB-Waschboxen',
 'Sanitär',
 'Shop',
 'Staubsauger',
 'Tankpool',
 'Verkehrsanbindung',
 'WLAN',
 'Waschanlage',
 'Werkstatt',
 'Zapfsäulen',
 'Öffnungszeiten'}

In [333]:
unflat = [[x] for x in flat_set]

In [334]:
label_vocab = build_vocab_from_iterator(unflat, min_freq=1, specials=["<unk>"])

label_vocab.set_default_index(vocab["<unk>"])

In [335]:
label_vocab.lookup_token(3)

'DigitalFueling'

#### Dictionary erstellen

In [336]:
label_dict = {label:i for i, label in enumerate(flat_set)}
label_dict

{'Personal': 0,
 'Verkehrsanbindung': 1,
 'Werkstatt': 2,
 'SB-Waschboxen': 3,
 'Kartenakzeptanzen': 4,
 'Erscheinungsbild': 5,
 'E-Fuels': 6,
 'Paketservice': 7,
 'WLAN': 8,
 'Shop': 9,
 'Pricing': 10,
 'Kraftstoffauswahl': 11,
 'Tankpool': 12,
 'DigitalFueling': 13,
 'Bistro': 14,
 'Zapfsäulen': 15,
 'Sanitär': 16,
 'Öffnungszeiten': 17,
 'Staubsauger': 18,
 'Nacht-/Tankautomat': 19,
 'Waschanlage': 20,
 'AdBlue': 21,
 'E-Mobilität': 22,
 'Luft': 23}

#### Tensor

In [337]:
doc2 = label_list_export[2]
doc2

['Personal', 'Waschanlage']

In [338]:
pos_vals = [label_dict[val] for val in doc2]
pos_vals

[0, 20]

In [339]:
labels = torch.LongTensor(pos_vals)
labels

tensor([ 0, 20])

In [340]:
y_onehot = nn.functional.one_hot(labels, num_classes=24)
y_onehot

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [341]:
y_onehot = y_onehot.sum(dim=0).float()
y_onehot

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0.])

In [342]:
# labels = torch.tensor([1,5,8,0])
# labels = labels.unsqueeze(0)
# target = torch.zeros(labels.size(0), 24).scatter_(1, labels, 1.)
# print(target)

### Erstellung Dataloader

In [343]:
# label_pipeline = lambda x: int(x) -1

In [344]:
def collate_batch(batch):
    label_list, text_list = [], []
 
    for (_text,_label) in batch:
    
        # Vorverarbeitung der Label
        # label_list.append(label_pipeline(_label))
        processed_labels = encode(_label, label_vocab)

        label_list.append(processed_labels)

        # Vorverarbeitung der Texte
        processed_text = encode(_text, vocab)
        
        # Zusammenführen sämtlicher Textrepräsentationen in einer Liste
        text_list.append(processed_text)
 
    # Zusammenführen aller Label in einem Tensor
    labels = torch.cat(label_list, dim=0)
    
    # Verbinden der Tensoren in text_list zu einem Tensor
    texts = torch.cat(text_list, dim = 0)

    # Ausgabe der Texte und der Label
    return texts.to(device), labels.to(device)

In [345]:
train_loader = DataLoader(
 train_set, batch_size=64,
 shuffle=True,
 collate_fn=collate_batch,
 num_workers=0
)

## Architektur und Training

### Architektur

In [346]:
class LinearTextClassificationModel(nn.Module):

    def __init__(self, vocab_size, num_class):
        super(LinearTextClassificationModel, self).__init__()
        self.fc1 = nn.Linear(vocab_size, 200)
        self.fc2 = nn.Linear(200, num_class)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        output = F.softmax(x, dim=1)
        return output

In [347]:
vocab_size = len(vocab)
num_class = 25
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

### Training

In [348]:
# Hyperparameter

## Festlegung Lernrate
learning_rate = 0.05

## Initialisierung Fehlerfunktion
loss_fn = nn.CrossEntropyLoss()

## Initialisierung Fehlerfunktion
bce_loss = nn.BCEWithLogitsLoss()

## Initialisierung Optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate, momentum=0.9)

## Definition der Epochen
num_epochs = 35

In [349]:
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True).to(device)

loss_hist = {}
accuracy_hist = {}

In [350]:
for (text, label) in train_loader:
    #print(label[[0][0]])
    #print(text)
    labelnew = label.type(torch.LongTensor)
    print(labelnew[[0][0]])

tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0])
tensor([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1])
tensor([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,


In [351]:
# Training
model.train()

for epoch in range(num_epochs):

    # Dokumentation Loss -> Erkennung ob Netz konvergiert
    running_loss = 0.0
    num_batches = 0

    for (text, label) in train_loader:
        num_batches += 1
        pred = model(text)

        # Der Fehler wird berechnet
        loss = bce_loss(pred, label)
        # Der Fehler wird über das Netz zurückpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        ## Bestimmung der Accuracy für den Batch
        train_accuracy(pred, label.type(torch.LongTensor))
        
        # running loss
        running_loss +=loss.item()
 
    loss_hist[epoch] = running_loss/num_batches
 
    batch_train_accuracy = train_accuracy.compute()
    print(f"Training Accuracy for epoch {epoch}:{batch_train_accuracy}")
    accuracy_hist[epoch] = batch_train_accuracy.cpu().item()
    train_accuracy.reset()

Training Accuracy for epoch 0:0.0
Training Accuracy for epoch 1:0.0
Training Accuracy for epoch 2:0.0
Training Accuracy for epoch 3:0.0
Training Accuracy for epoch 4:0.0
Training Accuracy for epoch 5:0.0
Training Accuracy for epoch 6:0.0
Training Accuracy for epoch 7:0.0
Training Accuracy for epoch 8:0.0
Training Accuracy for epoch 9:0.0
Training Accuracy for epoch 10:0.0
Training Accuracy for epoch 11:0.0
Training Accuracy for epoch 12:0.0
Training Accuracy for epoch 13:0.0
Training Accuracy for epoch 14:0.0
Training Accuracy for epoch 15:0.0
Training Accuracy for epoch 16:0.0
Training Accuracy for epoch 17:0.0
Training Accuracy for epoch 18:0.0
Training Accuracy for epoch 19:0.0
Training Accuracy for epoch 20:0.0
Training Accuracy for epoch 21:0.0
Training Accuracy for epoch 22:0.0
Training Accuracy for epoch 23:0.00035739815211854875
Training Accuracy for epoch 24:0.0021443888545036316
Training Accuracy for epoch 25:0.01751250959932804
Training Accuracy for epoch 26:0.06719084829092

### Auswertung Fehlerentwicklung

In [352]:
loss_df = pd.DataFrame.from_dict(loss_hist, orient= 'index').reset_index()

loss_df.columns = ['Epoch', 'Loss']
loss_df.head()

Epoch      Loss
0      0  0.709551
1      1  0.709498
2      2  0.709445
3      3  0.709391
4      4  0.709325

In [353]:
train_chart = alt.Chart(loss_df).mark_line().encode(
    x=alt.X('Epoch', title = 'Anzahl Epochen'),
    y=alt.Y('Loss', title = 'Mittlerer Fehler')
)
# glue('train-loss-team', train_chart,display=True)
train_chart

alt.Chart(...)

### Auswertung Genauigkeit

In [354]:
accuracy_df = pd.DataFrame.from_dict(accuracy_hist, orient = 'index').reset_index()
accuracy_df.columns = ['Epoch', 'Accuracy']
accuracy_df.head()

Epoch  Accuracy
0      0       0.0
1      1       0.0
2      2       0.0
3      3       0.0
4      4       0.0

In [355]:
accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
    x=alt.X('Epoch',title = 'Anzahl Epochen'),
    y=alt.Y('Accuracy', title = 'Genauigkeit')
)
accuracy_chart

alt.Chart(...)

## Evaluierung

In [356]:
model.eval()

LinearTextClassificationModel(
  (fc1): Linear(in_features=2397, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=25, bias=True)
)

### Gesamtevaluierung

In [357]:
test_loader = DataLoader(test_set, batch_size= 64, shuffle=True,collate_fn=collate_batch)

In [358]:
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True).to(device)

with torch.no_grad():
    for (text, label) in test_loader:
        # Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()

In [359]:
total_valid_accuracy

tensor(0.3328)

### Evaluierung nach Klassen

In [360]:
# Evaluieren
valid_accuracy = torchmetrics.Accuracy(
    average=None,
    num_classes=25
).to(device)

with torch.no_grad():
    for(text, label) in test_loader:
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()
    total_valid_accuracy

In [361]:
total_valid_accuracy

tensor([0.5371, 0.9900, 0.8265, 0.9958, 0.9992, 0.9975, 0.8716, 0.9666, 0.9266,
        0.9842, 0.9733, 0.9925, 0.6897, 0.7456, 0.9900, 0.9700, 0.8674, 0.9933,
        0.9992, 0.9750,    nan, 0.8774, 0.9867, 0.9908, 0.9708])

### Evaluierung nach der Anzahl der Epochen

In [362]:
train_loader = DataLoader(train_set, batch_size=64, shuffle=True, collate_fn=collate_batch)

In [363]:
test_loader = DataLoader(train_set, batch_size=64, shuffle=True, collate_fn=collate_batch)

In [364]:
vocab_size = len(vocab)
num_class = 25
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

In [365]:
bce_loss = nn.BCEWithLogitsLoss()

In [366]:
learning_rate = 0.05

optimizer = optim.SGD(
    model.parameters(),
    lr=learning_rate,
    momentum=0.9
)

In [367]:
num_epochs = 35

In [368]:
# Evaluierung wurd vorbereitet
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True).to(device)
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True).to(device)

train_accuracy_hist = {}
train_loss_hist = {}

valid_accuracy_hist = {}
valid_loss_hist = {}

In [369]:
for epoch in range(num_epochs):

    # Loss wird dokumentiert, sodass zu erkenne ist, ob das Netz konvergiert
    num_train_batches = 0
    num_eval_batches = 0
    train_running_loss = 0.0
    eval_running_loss = 0.0

    model.train()
    for (text, label) in train_loader:
        num_train_batches += 1
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        # Der Fehler wird berechnet
        # Als Ausgabe wird ein Tensor zurückgegeben
        loss = bce_loss(pred, label)
        # Der Fehler wird über das Netz zurükpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        # Aktualisierung des States der train_accurracy
        train_accuracy.update(pred, label.type(torch.LongTensor))
        # running loss
        train_running_loss += loss.item()

    train_loss_hist[epoch] = train_running_loss / num_train_batches

    # Berechnung der Trainingsgenauigkeit für die Epoche
    total_train_accuracy = train_accuracy.compute()
    # Hinzufügen der Trainingsgenauigkeit zu dem Dictionary
    train_accuracy_hist[epoch] = total_valid_accuracy.cpu().numpy()

    # Validierung
    model.eval()
    with torch.no_grad():
        for (text, label) in test_loader:
            num_eval_batches += 1
            # Die Vorhersage wird für das Model erzeugt
            pred = model(text)
            # Test loss
            eval_loss = bce_loss(pred, label)
            # Running loss
            eval_running_loss += eval_loss.item()
            # Aktualisierung des States der valid_accuracy
            valid_accuracy.update(pred, label.type(torch.LongTensor))
    
    valid_loss_hist[epoch] = eval_running_loss/num_eval_batches

    # Berechnung der Validierungsgenauigkeit für die Epoche
    total_valid_accuracy = valid_accuracy.compute()
    # Hinzufügen der Validierungsgenauigkeit zum Dictionary
    valid_accuracy_hist[epoch] = total_valid_accuracy.cpu().numpy()

    print(f"Training Accuracy for epoch {epoch}: {total_train_accuracy}")
    print(f"Validation Accuracy for epoch {epoch}: {total_valid_accuracy}")
    train_accuracy.reset()
    valid_accuracy.reset()



Training Accuracy for epoch 0: 0.0
Validation Accuracy for epoch 0: 0.0
Training Accuracy for epoch 1: 0.0
Validation Accuracy for epoch 1: 0.0
Training Accuracy for epoch 2: 0.0
Validation Accuracy for epoch 2: 0.0
Training Accuracy for epoch 3: 0.0
Validation Accuracy for epoch 3: 0.0
Training Accuracy for epoch 4: 0.0
Validation Accuracy for epoch 4: 0.0
Training Accuracy for epoch 5: 0.0
Validation Accuracy for epoch 5: 0.0
Training Accuracy for epoch 6: 0.0
Validation Accuracy for epoch 6: 0.0
Training Accuracy for epoch 7: 0.0
Validation Accuracy for epoch 7: 0.0
Training Accuracy for epoch 8: 0.0
Validation Accuracy for epoch 8: 0.0
Training Accuracy for epoch 9: 0.0
Validation Accuracy for epoch 9: 0.0
Training Accuracy for epoch 10: 0.0
Validation Accuracy for epoch 10: 0.0
Training Accuracy for epoch 11: 0.0
Validation Accuracy for epoch 11: 0.0
Training Accuracy for epoch 12: 0.0
Validation Accuracy for epoch 12: 0.0
Training Accuracy for epoch 13: 0.0
Validation Accuracy fo

In [371]:
train_loss_df = pd.DataFrame.from_dict(train_loss_hist, orient = "index").reset_index()
train_loss_df["type"] = "train"
valid_loss_df = pd.DataFrame.from_dict(valid_loss_hist, orient = "index").reset_index()
valid_loss_df["type"] = "validation"
loss_df = pd.concat([train_loss_df,valid_loss_df])
loss_df.columns = ["Epoch", "Loss", "Type"]

In [372]:
train_eval_loss_chart = alt.Chart(loss_df).mark_line().encode(
 x='Epoch',
 y='Loss',
 color='Type'
)
train_eval_loss_chart

alt.Chart(...)

In [378]:
valid_accuracy_hist

{0: array(0., dtype=float32),
 1: array(0., dtype=float32),
 2: array(0., dtype=float32),
 3: array(0., dtype=float32),
 4: array(0., dtype=float32),
 5: array(0., dtype=float32),
 6: array(0., dtype=float32),
 7: array(0., dtype=float32),
 8: array(0., dtype=float32),
 9: array(0., dtype=float32),
 10: array(0., dtype=float32),
 11: array(0., dtype=float32),
 12: array(0., dtype=float32),
 13: array(0., dtype=float32),
 14: array(0., dtype=float32),
 15: array(0., dtype=float32),
 16: array(0., dtype=float32),
 17: array(0., dtype=float32),
 18: array(0., dtype=float32),
 19: array(0., dtype=float32),
 20: array(0., dtype=float32),
 21: array(0., dtype=float32),
 22: array(0., dtype=float32),
 23: array(0., dtype=float32),
 24: array(0., dtype=float32),
 25: array(0.0007148, dtype=float32),
 26: array(0.00500357, dtype=float32),
 27: array(0.02894925, dtype=float32),
 28: array(0.09756969, dtype=float32),
 29: array(0.2119371, dtype=float32),
 30: array(0.2726948, dtype=float32),
 31:

In [380]:
train_accuracy_hist

{0: array([0.53711426, 0.98999166, 0.8265221 , 0.9958299 , 0.99916595,
        0.9974979 , 0.8715596 , 0.96663886, 0.9266055 , 0.98415345,
        0.97331107, 0.99249375, 0.68974143, 0.7456213 , 0.98999166,
        0.969975  , 0.8673895 , 0.9933278 , 0.99916595, 0.97497916,
               nan, 0.87739784, 0.98665553, 0.9908257 , 0.970809  ],
       dtype=float32),
 1: array(0., dtype=float32),
 2: array(0., dtype=float32),
 3: array(0., dtype=float32),
 4: array(0., dtype=float32),
 5: array(0., dtype=float32),
 6: array(0., dtype=float32),
 7: array(0., dtype=float32),
 8: array(0., dtype=float32),
 9: array(0., dtype=float32),
 10: array(0., dtype=float32),
 11: array(0., dtype=float32),
 12: array(0., dtype=float32),
 13: array(0., dtype=float32),
 14: array(0., dtype=float32),
 15: array(0., dtype=float32),
 16: array(0., dtype=float32),
 17: array(0., dtype=float32),
 18: array(0., dtype=float32),
 19: array(0., dtype=float32),
 20: array(0., dtype=float32),
 21: array(0., dtype=f

In [376]:
# print(type(list(train_accuracy_hist.items())))
# keys, values = np.array(list(train_accuracy_hist.items())).T
# print(values)

# Mittelwert/min/max berechnen, damit man nur einen wert pro epoche hat

In [375]:
train_accuracy_df = pd.DataFrame.from_dict(train_accuracy_hist, orient = "index").reset_index()
train_accuracy_df["type"] = "train"
valid_accuracy_df = pd.DataFrame.from_dict(valid_accuracy_hist, orient = "index").reset_index()
valid_accuracy_df["type"] = "validation"
accuracy_df = pd.concat([train_accuracy_df,valid_accuracy_df])
accuracy_df.columns = ["Epoch", "Accuracy", "Type"]

TypeError: iteration over a 0-d array

In [377]:
accuracy_df

Epoch  Accuracy
0       0  0.000000
1       1  0.000000
2       2  0.000000
3       3  0.000000
4       4  0.000000
5       5  0.000000
6       6  0.000000
7       7  0.000000
8       8  0.000000
9       9  0.000000
10     10  0.000000
11     11  0.000000
12     12  0.000000
13     13  0.000000
14     14  0.000000
15     15  0.000000
16     16  0.000000
17     17  0.000000
18     18  0.000000
19     19  0.000000
20     20  0.000000
21     21  0.000000
22     22  0.000000
23     23  0.000357
24     24  0.002144
25     25  0.017513
26     26  0.067191
27     27  0.167977
28     28  0.257327
29     29  0.309864
30     30  0.316655
31     31  0.316655
32     32  0.316655
33     33  0.316655
34     34  0.316655

In [ ]:
train_eval_accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
 x='Epoch',
 y='Accuracy',
 color='Type'
)
train_eval_accuracy_chart

alt.Chart(...)