# Import Bibliotheken

In [1]:
# Festlegung des Device
import platform

# Laden der Daten
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# Operationen mit Texten
import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
import spacy

# Modell
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim

# Evaluierung
import torchmetrics

# Auswertung der Evaluation
import pandas as pd
import altair as alt
import numpy as np

from sklearn import preprocessing

c:\Users\loedu\anaconda3\envs\ai_env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Package Versionen

In [2]:
for package in [torchtext,torch, torchmetrics, spacy, alt, pd]:
    print(f'{package.__name__}: {package.__version__}')

torchtext: 0.13.1
torch: 1.12.1
torchmetrics: 0.9.3
spacy: 3.4.2
altair: 4.2.0
pandas: 1.4.3


# Device Auswahl

In [3]:
device = torch.device(
    "cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

# Daten

## Dataset

### Erstellung Dataset

In [4]:
comment_df = pd.read_excel('../../data/clean/Google_Rezensionen.xlsx')
comment_df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

In [5]:
class TeamGoogleBewertungenDataSet(Dataset):

    def __init__(self, data):
        self.data = data
    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        text = comment_df.iloc[index]['Kommentar']
        category = comment_df.iloc[index]['Kategorien']
        return text, category

### Bestimmung Test- und Traningsdaten

In [6]:
# Bestimmung der Länge der Test- und Traningsdaten
dataset = TeamGoogleBewertungenDataSet(comment_df)
len_train = round(len(dataset)* 0.7)
len_test = round(len(dataset) * 0.3)
assert len(comment_df) == len_train + len_test

In [7]:
# Zufällige Aufsplittung der Anzahl von Test- und Trainingsdaten
train_set, test_set = torch.utils.data.random_split(dataset, [len_train, len_test]) 

In [8]:
# next(iter(train_set))

## Dataloader

### Tokenisierung

In [9]:
tokenizer = get_tokenizer(
    'spacy', 
    language='de_core_news_lg')

In [10]:
# Beispiel für Anwendung des tokenizer
# sentence = "This isn't a very long example."
# tokenizer(sentence)

### Erstellung Vokabular

In [11]:
def yield_tokens(data_iter):
    for text, _ in data_iter:
        yield tokenizer(text)

In [12]:
# Länge des Trainungsets
len(train_set)

2798

In [13]:
tokens = yield_tokens(train_set)

In [14]:
next(iter(tokens))

['war',
 'eigentlich',
 'immer',
 'zufrieden',
 'und',
 'habe',
 'mit',
 'dem',
 'firmenpkw',
 'so',
 'einiges',
 'an',
 'kraftstoff',
 'abgenommen',
 'dann',
 'meine',
 'frage',
 'ob',
 'der',
 'waschbeleg',
 'um',
 'einen',
 'tag',
 'verlängert',
 'werden',
 'kann',
 'weil',
 'ich',
 'es',
 'nicht',
 'geschafft',
 'habe',
 'antwort',
 'nein',
 'keine',
 'chance',
 'hmm',
 'ok',
 'habe',
 'schöne',
 'weihnachten',
 'gewünscht',
 'und',
 'suche',
 'mir',
 'jetzt',
 'eine',
 'andere',
 'tankstelle',
 'bevor',
 'jetzt',
 'kommt',
 'du',
 'hast',
 'doch',
 '4',
 'wochen',
 'zeit',
 'manchmal',
 'vergisst',
 'oder',
 'schafft',
 'man',
 'es',
 'eben',
 'nicht',
 'ich',
 'finde',
 'bei',
 'einem',
 'tag',
 'könnte',
 'man',
 'evtl',
 'etwas',
 'kulant',
 'sein',
 'aber',
 'wenn',
 'es',
 'so',
 'von',
 'oben',
 'angesagt',
 'ist',
 'dann',
 'hab',
 'ich',
 'das',
 'zu',
 'akzeptieren']

In [15]:
vocab = build_vocab_from_iterator(tokens, min_freq=2, specials=["<unk>"])

vocab.set_default_index(vocab["<unk>"])

In [16]:
len(vocab)

2412

In [17]:
vocab(['Hallo', 'sehr', 'Personal'])

[0, 3, 0]

In [18]:
vocab.lookup_token(0)

'<unk>'

### Encoding

In [19]:
onehot = torch.zeros(1,len(vocab))

In [20]:
pos = vocab(['nette', 'Bedienung', 'sauber'])
pos

[32, 0, 48]

In [21]:
def encode(text, vocab):
    tokens = tokenizer(text)
    onehot = torch.zeros(1,len(vocab))
    onehot[:,vocab(tokens)] = 1
    return onehot

### Multilabel Encoding

In [22]:
import torch
import torch.nn

In [23]:
df = comment_df.explode('Kategorien')
df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

#### Kategorien splitten

In [24]:
einzelLabels = comment_df['Kategorien'].str.split(',')
label_list_export = einzelLabels.to_list()
label_list_export

[['Personal', 'Shop', 'Bistro'],
 ['Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal'],
 ['Pricing', 'DigitalFueling'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing', 'Kraftstoffauswahl'],
 ['Personal', 'Öffnungszeiten'],
 ['Personal', 'SB-Waschboxen', 'Waschanlage'],
 ['Shop'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing'],
 ['Bistro'],
 ['Personal', 'Pricing', 'Shop', 'Waschanlage'],
 ['Personal'],
 ['Personal'],
 ['Bistro'],
 ['Erscheinungsbild'],
 ['Personal', 'Pricing'],
 ['Personal'],
 ['Personal'],
 ['Personal', 'Shop'],
 ['Erscheinungsbild'],
 ['Personal', 'Bistro'],
 ['Erscheinungsbild', 'Nacht-/Tankautomat', 'Waschanlage', 'Staubsauger'],
 ['Pricing'],
 ['Personal'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal'],
 ['Bistro'],
 ['Pricing', 'Kraftstoffauswahl'],
 ['Pricing'],
 ['Nacht-/Tankautomat'],
 ['Shop', 'Bistro'],
 ['Erscheinungsbild', 'Personal', 'Sanitär

##### In der nachfolgenden Zelle wird aus der verschachtelten Liste eine "flache Liste"

In [25]:
flat_list = []
for sublist in label_list_export:
    for item in sublist:
        flat_list.append(item)

flat_list

['Personal',
 'Shop',
 'Bistro',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'DigitalFueling',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Kraftstoffauswahl',
 'Personal',
 'Öffnungszeiten',
 'Personal',
 'SB-Waschboxen',
 'Waschanlage',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Bistro',
 'Personal',
 'Pricing',
 'Shop',
 'Waschanlage',
 'Personal',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Pricing',
 'Personal',
 'Personal',
 'Personal',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Nacht-/Tankautomat',
 'Waschanlage',
 'Staubsauger',
 'Pricing',
 'Personal',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Bistro',
 'Pricing',
 'Kraftstoffauswahl',
 'Pricing',
 'Nacht-/Tankautomat',
 'Shop',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Sanitär',
 'Bistro',
 'Pricing',
 'Verkehrsanbindung'

##### Doppelte Werte werden entfernt, so dass jeder Eintrag nur einmalig vorhanden ist. Dies erreichen wir mit set()

In [26]:
flat_set = set(flat_list)
flat_set

{'AdBlue',
 'Bistro',
 'DigitalFueling',
 'E-Fuels',
 'E-Mobilität',
 'Erscheinungsbild',
 'Kartenakzeptanzen',
 'Kraftstoffauswahl',
 'Luft',
 'Nacht-/Tankautomat',
 'Paketservice',
 'Personal',
 'Pricing',
 'SB-Waschboxen',
 'Sanitär',
 'Shop',
 'Staubsauger',
 'Tankpool',
 'Verkehrsanbindung',
 'WLAN',
 'Waschanlage',
 'Werkstatt',
 'Zapfsäulen',
 'Öffnungszeiten'}

In [27]:
unflat = [[x] for x in flat_set]

In [28]:
label_vocab = build_vocab_from_iterator(unflat, min_freq=1, specials=["<unk>"])

label_vocab.set_default_index(vocab["<unk>"])

In [29]:
label_vocab.lookup_token(3)

'DigitalFueling'

#### Dictionary erstellen

In [30]:
label_dict = {label:i for i, label in enumerate(flat_set)}
label_dict

{'Luft': 0,
 'E-Fuels': 1,
 'Nacht-/Tankautomat': 2,
 'Kraftstoffauswahl': 3,
 'Waschanlage': 4,
 'Bistro': 5,
 'Sanitär': 6,
 'WLAN': 7,
 'Zapfsäulen': 8,
 'Pricing': 9,
 'Kartenakzeptanzen': 10,
 'Tankpool': 11,
 'Öffnungszeiten': 12,
 'E-Mobilität': 13,
 'Paketservice': 14,
 'Verkehrsanbindung': 15,
 'Shop': 16,
 'Personal': 17,
 'AdBlue': 18,
 'Staubsauger': 19,
 'SB-Waschboxen': 20,
 'Erscheinungsbild': 21,
 'DigitalFueling': 22,
 'Werkstatt': 23}

#### Tensor

In [31]:
doc2 = label_list_export[2]
doc2

['Personal', 'Waschanlage']

In [32]:
pos_vals = [label_dict[val] for val in doc2]
pos_vals

[17, 4]

In [33]:
labels = torch.LongTensor(pos_vals)
labels

tensor([17,  4])

In [34]:
y_onehot = nn.functional.one_hot(labels, num_classes=24)
y_onehot

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
y_onehot = y_onehot.sum(dim=0).float()
y_onehot

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0.])

In [36]:
# labels = torch.tensor([1,5,8,0])
# labels = labels.unsqueeze(0)
# target = torch.zeros(labels.size(0), 24).scatter_(1, labels, 1.)
# print(target)

### Erstellung Dataloader

In [37]:
# label_pipeline = lambda x: int(x) -1

In [38]:
def collate_batch(batch):
    label_list, text_list = [], []
 
    for (_text,_label) in batch:
    
        # Vorverarbeitung der Label
        # label_list.append(label_pipeline(_label))
        processed_labels = encode(_label, label_vocab)

        label_list.append(processed_labels)

        # Vorverarbeitung der Texte
        processed_text = encode(_text, vocab)
        
        # Zusammenführen sämtlicher Textrepräsentationen in einer Liste
        text_list.append(processed_text)
 
    # Zusammenführen aller Label in einem Tensor
    labels = torch.cat(label_list, dim=0)
    
    # Verbinden der Tensoren in text_list zu einem Tensor
    texts = torch.cat(text_list, dim = 0)

    # Ausgabe der Texte und der Label
    return texts.to(device), labels.to(device)

In [39]:
train_loader = DataLoader(
 train_set, batch_size=16,
 shuffle=True,
 collate_fn=collate_batch,
 num_workers=0
)

## Architektur und Training

### Architektur

In [40]:
class LinearTextClassificationModel(nn.Module):

    def __init__(self, vocab_size, num_class):
        super(LinearTextClassificationModel, self).__init__()
        self.fc1 = nn.Linear(vocab_size, 200)
        self.fc2 = nn.Linear(200, num_class)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        output = F.softmax(x, dim=1)
        return output

In [41]:
vocab_size = len(vocab)
num_class = 25
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

### Training

In [42]:
# Hyperparameter

## Festlegung Lernrate
learning_rate = 0.1

## Initialisierung Fehlerfunktion
loss_fn = nn.MSELoss()

## Initialisierung Optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate, momentum=0.9)

## Definition der Epochen
num_epochs = 250

In [43]:
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)

loss_hist = {}
accuracy_hist = {}

In [44]:
for (text, label) in train_loader:
    #print(label[[0][0]])
    #print(text)
    labelnew = label.type(torch.LongTensor)
    print(labelnew[[0][0]])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1])
tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1])
tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,


In [45]:
# Training
model.train()

for epoch in range(num_epochs):

    # Dokumentation Loss -> Erkennung ob Netz konvergiert
    running_loss = 0.0
    num_batches = 0

    for (text, label) in train_loader:
        num_batches += 1
        pred = model(text)

        # Der Fehler wird berechnet
        loss = loss_fn(pred, label)
        # Der Fehler wird über das Netz zurückpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        ## Bestimmung der Accuracy für den Batch
        train_accuracy(pred, label.type(torch.LongTensor))
        
        # running loss
        running_loss +=loss.item()
 
    loss_hist[epoch] = running_loss/num_batches
 
    batch_train_accuracy = train_accuracy.compute()
    print(f"Training Accuracy for epoch {epoch}:{batch_train_accuracy}")
    accuracy_hist[epoch] = batch_train_accuracy.cpu().numpy()
    train_accuracy.reset()

Training Accuracy for epoch 0:0.0
Training Accuracy for epoch 1:0.0032165832817554474
Training Accuracy for epoch 2:0.0314510352909565
Training Accuracy for epoch 3:0.14581844210624695
Training Accuracy for epoch 4:0.20693352818489075
Training Accuracy for epoch 5:0.23766976594924927
Training Accuracy for epoch 6:0.2601858377456665
Training Accuracy for epoch 7:0.26876339316368103
Training Accuracy for epoch 8:0.27448177337646484
Training Accuracy for epoch 9:0.27626875042915344
Training Accuracy for epoch 10:0.28270193934440613
Training Accuracy for epoch 11:0.28377413749694824
Training Accuracy for epoch 12:0.2869907021522522
Training Accuracy for epoch 13:0.2880629003047943
Training Accuracy for epoch 14:0.28949248790740967
Training Accuracy for epoch 15:0.29199427366256714
Training Accuracy for epoch 16:0.29592564702033997
Training Accuracy for epoch 17:0.3109363913536072
Training Accuracy for epoch 18:0.32630449533462524
Training Accuracy for epoch 19:0.33273768424987793
Training 

In [46]:
total_train_accuracy = train_accuracy.compute()

c:\Users\loedu\anaconda3\envs\ai_env\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric Accuracy was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)


### Auswertung Fehlerentwicklung

In [47]:
loss_df = pd.DataFrame.from_dict(loss_hist, orient= 'index').reset_index()

loss_df.columns = ['Epoch', 'Loss']
loss_df.head()

Epoch      Loss
0      0  0.086538
1      1  0.078865
2      2  0.065017
3      3  0.062626
4      4  0.061636

In [48]:
train_chart = alt.Chart(loss_df).mark_line().encode(
    x=alt.X('Epoch', title = 'Anzahl Epochen'),
    y=alt.Y('Loss', title = 'Mittlerer Fehler')
)
# glue('train-loss-team', train_chart,display=True)
train_chart

alt.Chart(...)

### Auswertung Genauigkeit

In [49]:
accuracy_df = pd.DataFrame.from_dict(accuracy_hist, orient = 'index').reset_index()
accuracy_df.columns = ['Epoch', 'Accuracy']
accuracy_df.head()

Epoch  Accuracy
0      0  0.000000
1      1  0.003217
2      2  0.031451
3      3  0.145818
4      4  0.206934

In [50]:
accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
    x=alt.X('Epoch',title = 'Anzahl Epochen'),
    y=alt.Y('Accuracy', title = 'Genauigkeit')
)
accuracy_chart

alt.Chart(...)

## Evaluierung

In [51]:
model.eval()

LinearTextClassificationModel(
  (fc1): Linear(in_features=2412, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=25, bias=True)
)

### Gesamtevaluierung

In [52]:
test_loader = DataLoader(test_set, batch_size= 16, shuffle=True,collate_fn=collate_batch)

In [53]:
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)

with torch.no_grad():
    for (text, label) in test_loader:
        # Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()

In [54]:
total_valid_accuracy

tensor(0.4479)

### Evaluierung nach Klassen

In [55]:
# Evaluieren
valid_accuracy = torchmetrics.Accuracy(
    average=None,
    num_classes=25
).to(device)

with torch.no_grad():
    for(text, label) in test_loader:
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()
    total_valid_accuracy

In [56]:
total_valid_accuracy

tensor([0.6447, 0.9933, 0.8782, 0.9925,    nan, 0.9983, 0.8657, 0.9691, 0.9491,
        0.9750, 0.9817, 0.9942, 0.7773, 0.8699, 0.9850, 0.9658, 0.8791, 0.9842,
        0.9975, 0.9791, 0.9983, 0.9233, 0.9892, 0.9883, 0.9817])

### Evaluierung nach der Anzahl der Epochen

In [57]:
train_loader = DataLoader(train_set, batch_size=16, shuffle=True, collate_fn=collate_batch)

In [58]:
test_loader = DataLoader(test_set, batch_size=16, shuffle=True, collate_fn=collate_batch)

In [59]:
vocab_size = len(vocab)
num_class = 25
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

In [60]:
learning_rate = 0.1

loss_fn = nn.MSELoss()

optimizer = optim.SGD(model.parameters(),lr=learning_rate,momentum=0.9)

num_epochs = 250

In [61]:
# Evaluierung wurd vorbereitet
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True,threshold=0.6).to(device)

train_accuracy_hist = {}
train_loss_hist = {}

valid_accuracy_hist = {}
valid_loss_hist = {}

In [62]:
for epoch in range(num_epochs):

    # Loss wird dokumentiert, sodass zu erkenne ist, ob das Netz konvergiert
    num_train_batches = 0
    num_eval_batches = 0
    train_running_loss = 0.0
    eval_running_loss = 0.0

    model.train()
    for (text, label) in train_loader:
        num_train_batches += 1
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        # Der Fehler wird berechnet
        # Als Ausgabe wird ein Tensor zurückgegeben
        loss = loss_fn(pred, label)
        # Der Fehler wird über das Netz zurükpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        # Aktualisierung des States der train_accurracy
        train_accuracy.update(pred, label.type(torch.LongTensor))
        # running loss
        train_running_loss += loss.item()

    train_loss_hist[epoch] = train_running_loss / num_train_batches

    # Berechnung der Trainingsgenauigkeit für die Epoche
    total_train_accuracy = train_accuracy.compute()
    # Hinzufügen der Trainingsgenauigkeit zu dem Dictionary
    train_accuracy_hist[epoch] = total_train_accuracy.cpu().numpy()

    # Validierung
    model.eval()
    with torch.no_grad():
        for (text, label) in test_loader:
            num_eval_batches += 1
            # Die Vorhersage wird für das Model erzeugt
            pred = model(text)
            # Test loss
            eval_loss = loss_fn(pred, label)
            # Running loss
            eval_running_loss += eval_loss.item()
            # Aktualisierung des States der valid_accuracy
            valid_accuracy.update(pred, label.type(torch.LongTensor))
    
    valid_loss_hist[epoch] = eval_running_loss/num_eval_batches

    # Berechnung der Validierungsgenauigkeit für die Epoche
    total_valid_accuracy = valid_accuracy.compute()
    # Hinzufügen der Validierungsgenauigkeit zum Dictionary
    valid_accuracy_hist[epoch] = total_valid_accuracy.cpu().numpy()

    print(f"Training Accuracy for epoch {epoch}: {total_train_accuracy}")
    print(f"Validation Accuracy for epoch {epoch}: {total_valid_accuracy}")
    train_accuracy.reset()
    valid_accuracy.reset()

Training Accuracy for epoch 0: 0.0
Validation Accuracy for epoch 0: 0.0
Training Accuracy for epoch 1: 0.0007147963042370975
Validation Accuracy for epoch 1: 0.005838198587298393
Training Accuracy for epoch 2: 0.013581129722297192
Validation Accuracy for epoch 2: 0.03169307857751846
Training Accuracy for epoch 3: 0.12365975975990295
Validation Accuracy for epoch 3: 0.1618015021085739
Training Accuracy for epoch 4: 0.19478198885917664
Validation Accuracy for epoch 4: 0.23269391059875488
Training Accuracy for epoch 5: 0.23195140063762665
Validation Accuracy for epoch 5: 0.2702251970767975
Training Accuracy for epoch 6: 0.25339528918266296
Validation Accuracy for epoch 6: 0.2827356159687042
Training Accuracy for epoch 7: 0.2673338055610657
Validation Accuracy for epoch 7: 0.28190159797668457
Training Accuracy for epoch 8: 0.27269479632377625
Validation Accuracy for epoch 8: 0.2835696339607239
Training Accuracy for epoch 9: 0.27448177337646484
Validation Accuracy for epoch 9: 0.30358633399

In [63]:
train_loss_df = pd.DataFrame.from_dict(train_loss_hist, orient = "index").reset_index()
train_loss_df["type"] = "Train"
valid_loss_df = pd.DataFrame.from_dict(valid_loss_hist, orient = "index").reset_index()
valid_loss_df["type"] = "Test"
loss_df = pd.concat([train_loss_df,valid_loss_df])
loss_df.columns = ["Epoch", "Loss", "Type"]

In [64]:
train_eval_loss_chart = alt.Chart(loss_df).mark_line().encode(
    x = alt.X('Epoch', title='Anzahl Epochen'),
    y = alt.Y('Loss',title='Mittlerer Fehler'),
    color = alt.Color('Type',title='Typ')
)
train_eval_loss_chart

alt.Chart(...)

In [65]:
valid_accuracy_hist

{0: array(0., dtype=float32),
 1: array(0.0058382, dtype=float32),
 2: array(0.03169308, dtype=float32),
 3: array(0.1618015, dtype=float32),
 4: array(0.23269391, dtype=float32),
 5: array(0.2702252, dtype=float32),
 6: array(0.28273562, dtype=float32),
 7: array(0.2819016, dtype=float32),
 8: array(0.28356963, dtype=float32),
 9: array(0.30358633, dtype=float32),
 10: array(0.29774812, dtype=float32),
 11: array(0.3002502, dtype=float32),
 12: array(0.29858217, dtype=float32),
 13: array(0.30525437, dtype=float32),
 14: array(0.3110926, dtype=float32),
 15: array(0.3085905, dtype=float32),
 16: array(0.31276062, dtype=float32),
 17: array(0.3294412, dtype=float32),
 18: array(0.33944955, dtype=float32),
 19: array(0.35195997, dtype=float32),
 20: array(0.35529608, dtype=float32),
 21: array(0.35696414, dtype=float32),
 22: array(0.36363637, dtype=float32),
 23: array(0.3653044, dtype=float32),
 24: array(0.36613846, dtype=float32),
 25: array(0.37114263, dtype=float32),
 26: array(0.

In [66]:
train_accuracy_hist

{0: array(0., dtype=float32),
 1: array(0.0007148, dtype=float32),
 2: array(0.01358113, dtype=float32),
 3: array(0.12365976, dtype=float32),
 4: array(0.19478199, dtype=float32),
 5: array(0.2319514, dtype=float32),
 6: array(0.2533953, dtype=float32),
 7: array(0.2673338, dtype=float32),
 8: array(0.2726948, dtype=float32),
 9: array(0.27448177, dtype=float32),
 10: array(0.28091493, dtype=float32),
 11: array(0.28270194, dtype=float32),
 12: array(0.2859185, dtype=float32),
 13: array(0.2866333, dtype=float32),
 14: array(0.2873481, dtype=float32),
 15: array(0.29092208, dtype=float32),
 16: array(0.29342386, dtype=float32),
 17: array(0.3045032, dtype=float32),
 18: array(0.32022873, dtype=float32),
 19: array(0.3295211, dtype=float32),
 20: array(0.33559686, dtype=float32),
 21: array(0.33917084, dtype=float32),
 22: array(0.34167263, dtype=float32),
 23: array(0.3445318, dtype=float32),
 24: array(0.349178, dtype=float32),
 25: array(0.3498928, dtype=float32),
 26: array(0.35060

In [67]:
# Erste Epoche löschen, da diese nicht neu initialisiert wird und Daten aus vorherigen Schritten enthält

del train_accuracy_hist[0]
del valid_accuracy_hist[0]

In [68]:
train_accuracy_df = pd.DataFrame.from_dict(train_accuracy_hist, orient = "index").reset_index()
train_accuracy_df["type"] = "Train"
valid_accuracy_df = pd.DataFrame.from_dict(valid_accuracy_hist, orient = "index").reset_index()
valid_accuracy_df["type"] = "Test"
accuracy_df = pd.concat([train_accuracy_df,valid_accuracy_df])
accuracy_df.columns = ["Epoch", "Accuracy", "Type"]

In [69]:
accuracy_df

Epoch  Accuracy   Type
0        1  0.000715  Train
1        2  0.013581  Train
2        3  0.123660  Train
3        4  0.194782  Train
4        5  0.231951  Train
..     ...       ...    ...
244    245  0.441201   Test
245    246  0.441201   Test
246    247  0.441201   Test
247    248  0.441201   Test
248    249  0.441201   Test

[498 rows x 3 columns]

In [70]:
train_eval_accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
    x = alt.X('Epoch',title='Anzahl Epochen'),
    y = alt.Y('Accuracy',title='Genauigkeit'),
    color = alt.Color('Type',title='Typ')
)
train_eval_accuracy_chart

alt.Chart(...)