# Import Bibliotheken

In [78]:
# Festlegung des Device
import platform

# Laden der Daten
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# Operationen mit Texten
import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
import spacy

# Modell
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim

# Evaluierung
import torchmetrics

# Auswertung der Evaluation
import pandas as pd
import altair as alt
import numpy as np

from sklearn import preprocessing

### Package Versionen

In [79]:
for package in [torchtext,torch, torchmetrics, spacy, alt, pd]:
    print(f'{package.__name__}: {package.__version__}')

torchtext: 0.13.1
torch: 1.12.1
torchmetrics: 0.9.3
spacy: 3.4.2
altair: 4.2.0
pandas: 1.4.3


# Device Auswahl

In [80]:
device = torch.device(
    "cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

# Daten

## Dataset

### Erstellung Dataset

In [81]:
comment_df = pd.read_excel('../data/clean/Google_Rezensionen.xlsx')
comment_df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

In [82]:
class TeamGoogleBewertungenDataSet(Dataset):

    def __init__(self, data):
        self.data = data
    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        text = comment_df.iloc[index]['Kommentar']
        category = comment_df.iloc[index]['Kategorien']
        return text, category

### Bestimmung Test- und Traningsdaten

In [83]:
# Bestimmung der Länge der Test- und Traningsdaten
dataset = TeamGoogleBewertungenDataSet(comment_df)
len_train = round(len(dataset)* 0.7)
len_test = round(len(dataset) * 0.3)
assert len(comment_df) == len_train + len_test

In [84]:
# Zufällige Aufsplittung der Anzahl von Test- und Trainingsdaten
train_set, test_set = torch.utils.data.random_split(dataset, [len_train, len_test]) 

In [85]:
# next(iter(train_set))

## Dataloader

### Tokenisierung

In [86]:
tokenizer = get_tokenizer(
    'spacy', 
    language='de_core_news_lg')

In [87]:
# Beispiel für Anwendung des tokenizer
# sentence = "This isn't a very long example."
# tokenizer(sentence)

### Erstellung Vokabular

In [88]:
def yield_tokens(data_iter):
    for text, _ in data_iter:
        yield tokenizer(text)

In [89]:
# Länge des Trainungsets
len(train_set)

2798

In [90]:
tokens = yield_tokens(train_set)

In [91]:
next(iter(tokens))

['eine',
 'ordentliche',
 'und',
 'saubere',
 'tankstelle',
 'mit',
 'backshop',
 'die',
 'produkte',
 'sahen',
 'sehr',
 'lecker',
 'und',
 'frisch',
 'aus',
 'der',
 'service',
 'war',
 'einwandfrei']

In [92]:
vocab = build_vocab_from_iterator(tokens, min_freq=2, specials=["<unk>"])

vocab.set_default_index(vocab["<unk>"])

In [93]:
len(vocab)

2367

In [94]:
vocab(['Hallo', 'sehr', 'Personal'])

[0, 3, 0]

In [95]:
vocab.lookup_token(0)

'<unk>'

### Encoding

In [96]:
onehot = torch.zeros(1,len(vocab))

In [97]:
pos = vocab(['nette', 'Bedienung', 'sauber'])
pos

[30, 0, 51]

In [98]:
def encode(text, vocab):
    tokens = tokenizer(text)
    onehot = torch.zeros(1,len(vocab))
    onehot[:,vocab(tokens)] = 1
    return onehot

### Multilabel Encoding

In [99]:
import torch
import torch.nn

In [100]:
df = comment_df.explode('Kategorien')
df

Unnamed: 0      Tankstellenname               Datum  Bewertung  \
0              4     TS Schleswig MC  2022-09-30 06:46:42          5   
1              5          TS Prisdorf 2022-09-29 17:22:44          5   
2              6          TS Wanderup 2022-09-29 15:38:02          5   
3             10         TS Handewitt 2022-09-28 17:05:28          5   
4             12            TS Bremen 2022-09-28 04:24:34          4   
...          ...                  ...                 ...        ...   
3992       11072             TS Jübek 2015-04-07 17:45:02          5   
3993       11077             TS Jübek 2014-07-16 07:08:37          5   
3994       11079  TS Neustadt am Rüb. 2013-09-21 15:26:28          5   
3995       11080     TS Handewitt(SP) 2012-11-05 11:16:00          5   
3996       11081     TS Handewitt(SP) 2011-07-26 17:42:28          4   

                                              Kommentar  \
0     super nettes personal gutes frühstück mit groß...   
1                            sehr höfliche bedienstete    
2     immer gerne dort nettes und zuvorkommendes per...   
3                         nettes freundliches personal    
4     normale tankstelle die aber in der tank app ni...   
...                                                 ...   
3992  dies ist einfach die beste tankstelle die ich ...   
3993  sehr gut günstig guter shop und einige andere ...   
3994               öffnungszeiten mo so 06 00 22 00 uhr   
3995  genug platz fuer wohnwagen rechts beim autogas...   
3996  ideal um kurz vor dänemark nochmal günstig zu ...   

                                             Kategorien  
0                                  Personal,Shop,Bistro  
1                                              Personal  
2                                  Personal,Waschanlage  
3                                              Personal  
4                                Pricing,DigitalFueling  
...                                                 ...  
3992                      Kraftstoffauswahl,Waschanlage  
3993  Pricing,Shop,Kraftstoffauswahl,Waschanlage,Sta...  
3994                                     Öffnungszeiten  
3995                         Personal,Kraftstoffauswahl  
3996                                            Pricing  

[3997 rows x 6 columns]

#### Kategorien splitten

In [101]:
einzelLabels = comment_df['Kategorien'].str.split(',')
label_list_export = einzelLabels.to_list()
label_list_export

[['Personal', 'Shop', 'Bistro'],
 ['Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal'],
 ['Pricing', 'DigitalFueling'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing', 'Kraftstoffauswahl'],
 ['Personal', 'Öffnungszeiten'],
 ['Personal', 'SB-Waschboxen', 'Waschanlage'],
 ['Shop'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal', 'Waschanlage'],
 ['Personal', 'Pricing'],
 ['Personal', 'Pricing'],
 ['Bistro'],
 ['Personal', 'Pricing', 'Shop', 'Waschanlage'],
 ['Personal'],
 ['Personal'],
 ['Bistro'],
 ['Erscheinungsbild'],
 ['Personal', 'Pricing'],
 ['Personal'],
 ['Personal'],
 ['Personal', 'Shop'],
 ['Erscheinungsbild'],
 ['Personal', 'Bistro'],
 ['Erscheinungsbild', 'Nacht-/Tankautomat', 'Waschanlage', 'Staubsauger'],
 ['Pricing'],
 ['Personal'],
 ['Erscheinungsbild', 'Personal'],
 ['Personal'],
 ['Bistro'],
 ['Pricing', 'Kraftstoffauswahl'],
 ['Pricing'],
 ['Nacht-/Tankautomat'],
 ['Shop', 'Bistro'],
 ['Erscheinungsbild', 'Personal', 'Sanitär

##### In der nachfolgenden Zelle wird aus der verschachtelten Liste eine "flache Liste"

In [102]:
flat_list = []
for sublist in label_list_export:
    for item in sublist:
        flat_list.append(item)

flat_list

['Personal',
 'Shop',
 'Bistro',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'DigitalFueling',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Kraftstoffauswahl',
 'Personal',
 'Öffnungszeiten',
 'Personal',
 'SB-Waschboxen',
 'Waschanlage',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Waschanlage',
 'Personal',
 'Pricing',
 'Personal',
 'Pricing',
 'Bistro',
 'Personal',
 'Pricing',
 'Shop',
 'Waschanlage',
 'Personal',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Pricing',
 'Personal',
 'Personal',
 'Personal',
 'Shop',
 'Erscheinungsbild',
 'Personal',
 'Bistro',
 'Erscheinungsbild',
 'Nacht-/Tankautomat',
 'Waschanlage',
 'Staubsauger',
 'Pricing',
 'Personal',
 'Erscheinungsbild',
 'Personal',
 'Personal',
 'Bistro',
 'Pricing',
 'Kraftstoffauswahl',
 'Pricing',
 'Nacht-/Tankautomat',
 'Shop',
 'Bistro',
 'Erscheinungsbild',
 'Personal',
 'Sanitär',
 'Bistro',
 'Pricing',
 'Verkehrsanbindung'

##### Doppelte Werte werden entfernt, so dass jeder Eintrag nur einmalig vorhanden ist. Dies erreichen wir mit set()

In [103]:
flat_set = set(flat_list)
flat_set

{'AdBlue',
 'Bistro',
 'DigitalFueling',
 'E-Fuels',
 'E-Mobilität',
 'Erscheinungsbild',
 'Kartenakzeptanzen',
 'Kraftstoffauswahl',
 'Luft',
 'Nacht-/Tankautomat',
 'Paketservice',
 'Personal',
 'Pricing',
 'SB-Waschboxen',
 'Sanitär',
 'Shop',
 'Staubsauger',
 'Tankpool',
 'Verkehrsanbindung',
 'WLAN',
 'Waschanlage',
 'Werkstatt',
 'Zapfsäulen',
 'Öffnungszeiten'}

In [104]:
unflat = [[x] for x in flat_set]

In [105]:
label_vocab = build_vocab_from_iterator(unflat, min_freq=1,)

label_vocab.set_default_index(vocab["<unk>"])

In [106]:
label_vocab.lookup_token(3)

'E-Fuels'

#### Dictionary erstellen

In [107]:
label_dict = {label:i for i, label in enumerate(flat_set)}
label_dict

{'SB-Waschboxen': 0,
 'Verkehrsanbindung': 1,
 'Öffnungszeiten': 2,
 'Pricing': 3,
 'Tankpool': 4,
 'Paketservice': 5,
 'Staubsauger': 6,
 'AdBlue': 7,
 'Werkstatt': 8,
 'Zapfsäulen': 9,
 'E-Mobilität': 10,
 'DigitalFueling': 11,
 'Erscheinungsbild': 12,
 'WLAN': 13,
 'Nacht-/Tankautomat': 14,
 'E-Fuels': 15,
 'Bistro': 16,
 'Sanitär': 17,
 'Luft': 18,
 'Kartenakzeptanzen': 19,
 'Shop': 20,
 'Waschanlage': 21,
 'Personal': 22,
 'Kraftstoffauswahl': 23}

#### Tensor

In [108]:
doc2 = label_list_export[2]
doc2

['Personal', 'Waschanlage']

In [109]:
pos_vals = [label_dict[val] for val in doc2]
pos_vals

[22, 21]

In [110]:
labels = torch.LongTensor(pos_vals)
labels

tensor([22, 21])

In [111]:
y_onehot = nn.functional.one_hot(labels, num_classes=24)
y_onehot

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [112]:
y_onehot = y_onehot.sum(dim=0).float()
y_onehot

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0.])

In [113]:
# labels = torch.tensor([1,5,8,0])
# labels = labels.unsqueeze(0)
# target = torch.zeros(labels.size(0), 24).scatter_(1, labels, 1.)
# print(target)

### Erstellung Dataloader

In [114]:
# label_pipeline = lambda x: int(x) -1

In [115]:
def collate_batch(batch):
    label_list, text_list = [], []
 
    for (_text,_label) in batch:
    
        # Vorverarbeitung der Label
        # label_list.append(label_pipeline(_label))
        processed_labels = encode(_label, label_vocab)

        label_list.append(processed_labels)

        # Vorverarbeitung der Texte
        processed_text = encode(_text, vocab)
        
        # Zusammenführen sämtlicher Textrepräsentationen in einer Liste
        text_list.append(processed_text)
 
    # Zusammenführen aller Label in einem Tensor
    labels = torch.cat(label_list, dim=0)
    
    # Verbinden der Tensoren in text_list zu einem Tensor
    texts = torch.cat(text_list, dim = 0)

    # Ausgabe der Texte und der Label
    return texts.to(device), labels.to(device)

In [116]:
train_loader = DataLoader(
 train_set, batch_size=64,
 shuffle=True,
 collate_fn=collate_batch,
 num_workers=0
)

## Architektur und Training

### Architektur

In [117]:
class LinearTextClassificationModel(nn.Module):

    def __init__(self, vocab_size, num_class):
        super(LinearTextClassificationModel, self).__init__()
        self.fc1 = nn.Linear(vocab_size, 200)
        self.fc2 = nn.Linear(200, num_class)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        output = F.softmax(x, dim=1)
        return output

In [118]:
vocab_size = len(vocab)
num_class = flat_set.__len__()
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

### Training

In [119]:
# Hyperparameter

## Festlegung Lernrate
learning_rate = 0.03

## Initialisierung Fehlerfunktion
loss_fn = nn.CrossEntropyLoss()

## Initialisierung Fehlerfunktion
bce_loss = nn.MSELoss()#nn.BCEWithLogitsLoss()

## Initialisierung Optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate, momentum=0.9)

## Definition der Epochen
num_epochs = 150

In [120]:
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True, threshold= 0.5).to(device)

loss_hist = {}
accuracy_hist = {}

In [121]:
for (text, label) in train_loader:
    #print(label[[0][0]])
    #print(text)
    labelnew = label.type(torch.LongTensor)
    print(labelnew[[0][0]])

tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0,

In [122]:
# Training
model.train()

for epoch in range(num_epochs):

    # Dokumentation Loss -> Erkennung ob Netz konvergiert
    running_loss = 0.0
    num_batches = 0

    for (text, label) in train_loader:
        num_batches += 1
        pred = model(text)

        # Der Fehler wird berechnet
        loss = bce_loss(pred, label)
        # Der Fehler wird über das Netz zurückpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        ## Bestimmung der Accuracy für den Batch
        train_accuracy(pred, label.type(torch.LongTensor))
        
        # running loss
        running_loss +=loss.item()
 
    loss_hist[epoch] = running_loss/num_batches
 
    batch_train_accuracy = train_accuracy.compute()
    print(f"Training Accuracy for epoch {epoch}:{batch_train_accuracy}")
    accuracy_hist[epoch] = batch_train_accuracy.cpu().item()
    train_accuracy.reset()

Training Accuracy for epoch 0:0.0
Training Accuracy for epoch 1:0.0
Training Accuracy for epoch 2:0.0
Training Accuracy for epoch 3:0.0
Training Accuracy for epoch 4:0.0
Training Accuracy for epoch 5:0.0
Training Accuracy for epoch 6:0.0
Training Accuracy for epoch 7:0.0
Training Accuracy for epoch 8:0.0
Training Accuracy for epoch 9:0.0
Training Accuracy for epoch 10:0.0
Training Accuracy for epoch 11:0.0
Training Accuracy for epoch 12:0.0
Training Accuracy for epoch 13:0.0
Training Accuracy for epoch 14:0.0
Training Accuracy for epoch 15:0.0
Training Accuracy for epoch 16:0.0
Training Accuracy for epoch 17:0.0
Training Accuracy for epoch 18:0.0
Training Accuracy for epoch 19:0.00035739815211854875
Training Accuracy for epoch 20:0.00285918521694839
Training Accuracy for epoch 21:0.012151536531746387
Training Accuracy for epoch 22:0.028591850772500038
Training Accuracy for epoch 23:0.05325232446193695
Training Accuracy for epoch 24:0.07255182415246964
Training Accuracy for epoch 25:0.0

In [123]:
batch_train_accuracy

tensor(0.3134)

### Auswertung Fehlerentwicklung

In [124]:
loss_df = pd.DataFrame.from_dict(loss_hist, orient= 'index').reset_index()

loss_df.columns = ['Epoch', 'Loss']
loss_df.head()

Epoch      Loss
0      0  0.089336
1      1  0.089141
2      2  0.089021
3      3  0.088888
4      4  0.088706

In [125]:
train_chart = alt.Chart(loss_df).mark_line().encode(
    x=alt.X('Epoch', title = 'Anzahl Epochen'),
    y=alt.Y('Loss', title = 'Mittlerer Fehler')
).properties(title='Trainingsfehlerentwicklung in Abhängigkeit von der Anzahl der Epochen')
train_chart

alt.Chart(...)

### Auswertung Genauigkeit

In [126]:
accuracy_df = pd.DataFrame.from_dict(accuracy_hist, orient = 'index').reset_index()
accuracy_df.columns = ['Epoch', 'Accuracy']
accuracy_df.head()

Epoch  Accuracy
0      0       0.0
1      1       0.0
2      2       0.0
3      3       0.0
4      4       0.0

In [127]:
accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
    x=alt.X('Epoch',title = 'Anzahl Epochen'),
    y=alt.Y('Accuracy', title = 'Genauigkeit')
).properties(title='Trainingsgenauigkeit in Abhängigkeit von der Anzahl der Epochen')
accuracy_chart

alt.Chart(...)

## Evaluierung

In [128]:
model.eval()

LinearTextClassificationModel(
  (fc1): Linear(in_features=2367, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=24, bias=True)
)

### Gesamtevaluierung

In [129]:
test_loader = DataLoader(test_set, batch_size= 64, shuffle=True,collate_fn=collate_batch)

In [130]:
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True, threshold=0.5).to(device)

with torch.no_grad():
    for (text, label) in test_loader:
        # Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()

In [131]:
total_valid_accuracy

tensor(0.2936)

### Evaluierung nach Klassen

In [132]:
# Evaluieren
valid_accuracy = torchmetrics.Accuracy(
    average=None,
    num_classes=flat_set.__len__(),
    # subset_accuracy = True
).to(device)

with torch.no_grad():
    for(text, label) in test_loader:
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        valid_accuracy.update(pred, label.type(torch.LongTensor))
    total_valid_accuracy = valid_accuracy.compute()
    total_valid_accuracy

In [133]:
total_valid_accuracy # Werte sind zu hoch,da vermutlich eine Nichzuordnung als Zuordnung interpretiert wird

tensor([0.6172, 0.8224, 0.9917, 0.9992, 0.9983, 0.8449, 0.9616, 0.9266, 0.9791,
        0.9716, 0.9925, 0.8474, 0.7506, 0.9892, 0.9658, 0.8515, 0.9900,    nan,
        0.9633, 0.9992, 0.8932, 0.9875, 0.9867, 0.9641])

### Evaluierung nach der Anzahl der Epochen

In [134]:
train_loader = DataLoader(train_set, batch_size=64, shuffle=True, collate_fn=collate_batch)

In [135]:
test_loader = DataLoader(test_set, batch_size=64, shuffle=True, collate_fn=collate_batch)

In [136]:
vocab_size = len(vocab)
num_class = flat_set.__len__()
model = LinearTextClassificationModel(vocab_size, num_class).to(device)

In [137]:
bce_loss = nn.MSELoss()#nn.BCEWithLogitsLoss()

In [138]:
learning_rate = 0.03

optimizer = optim.SGD(model.parameters(),lr=learning_rate,momentum=0.9)

In [139]:
num_epochs = 150

In [140]:
# Evaluierung wurd vorbereitet
train_accuracy = torchmetrics.Accuracy(subset_accuracy=True, threshold=0.5).to(device)
valid_accuracy = torchmetrics.Accuracy(subset_accuracy=True, threshold=0.5).to(device)

train_accuracy_hist = {}
train_loss_hist = {}

valid_accuracy_hist = {}
valid_loss_hist = {}

In [141]:
for epoch in range(num_epochs):

    # Loss wird dokumentiert, sodass zu erkenne ist, ob das Netz konvergiert
    num_train_batches = 0
    num_eval_batches = 0
    train_running_loss = 0.0
    eval_running_loss = 0.0

    model.train()
    for (text, label) in train_loader:
        num_train_batches += 1
        # Die Vorhersage wird für das Model erzeugt
        pred = model(text)
        # Der Fehler wird berechnet
        # Als Ausgabe wird ein Tensor zurückgegeben
        loss = bce_loss(pred, label)
        # Der Fehler wird über das Netz zurükpropagiert
        loss.backward()
        # Die Gewichte werden angepasst
        optimizer.step()
        # Gradienten zurücksetzen
        optimizer.zero_grad()
        # Aktualisierung des States der train_accurracy
        train_accuracy.update(pred, label.type(torch.LongTensor))
        # running loss
        train_running_loss += loss.item()

    train_loss_hist[epoch] = train_running_loss / num_train_batches

    # Berechnung der Trainingsgenauigkeit für die Epoche
    total_train_accuracy = train_accuracy.compute()
    # Hinzufügen der Trainingsgenauigkeit zu dem Dictionary
    train_accuracy_hist[epoch] = total_valid_accuracy.cpu().numpy()

    # Validierung
    model.eval()
    with torch.no_grad():
        for (text, label) in test_loader:
            num_eval_batches += 1
            # Die Vorhersage wird für das Model erzeugt
            pred = model(text)
            # Test loss
            eval_loss = bce_loss(pred, label)
            # Running loss
            eval_running_loss += eval_loss.item()
            # Aktualisierung des States der valid_accuracy
            valid_accuracy.update(pred, label.type(torch.LongTensor))
    
    valid_loss_hist[epoch] = eval_running_loss/num_eval_batches

    # Berechnung der Validierungsgenauigkeit für die Epoche
    total_valid_accuracy = valid_accuracy.compute()
    # Hinzufügen der Validierungsgenauigkeit zum Dictionary
    valid_accuracy_hist[epoch] = total_valid_accuracy.cpu().numpy()

    print(f"Training Accuracy for epoch {epoch}: {total_train_accuracy}")
    print(f"Validation Accuracy for epoch {epoch}: {total_valid_accuracy}")
    train_accuracy.reset()
    valid_accuracy.reset()



Training Accuracy for epoch 0: 0.0
Validation Accuracy for epoch 0: 0.0
Training Accuracy for epoch 1: 0.0
Validation Accuracy for epoch 1: 0.0
Training Accuracy for epoch 2: 0.0
Validation Accuracy for epoch 2: 0.0
Training Accuracy for epoch 3: 0.0
Validation Accuracy for epoch 3: 0.0
Training Accuracy for epoch 4: 0.0
Validation Accuracy for epoch 4: 0.0
Training Accuracy for epoch 5: 0.0
Validation Accuracy for epoch 5: 0.0
Training Accuracy for epoch 6: 0.0
Validation Accuracy for epoch 6: 0.0
Training Accuracy for epoch 7: 0.0
Validation Accuracy for epoch 7: 0.0
Training Accuracy for epoch 8: 0.0
Validation Accuracy for epoch 8: 0.0
Training Accuracy for epoch 9: 0.0
Validation Accuracy for epoch 9: 0.0
Training Accuracy for epoch 10: 0.0
Validation Accuracy for epoch 10: 0.0
Training Accuracy for epoch 11: 0.0
Validation Accuracy for epoch 11: 0.0
Training Accuracy for epoch 12: 0.0
Validation Accuracy for epoch 12: 0.0
Training Accuracy for epoch 13: 0.0
Validation Accuracy fo

In [142]:
train_loss_df = pd.DataFrame.from_dict(train_loss_hist, orient = "index").reset_index()
train_loss_df["type"] = "train"
valid_loss_df = pd.DataFrame.from_dict(valid_loss_hist, orient = "index").reset_index()
valid_loss_df["type"] = "test"
loss_df = pd.concat([train_loss_df,valid_loss_df])
loss_df.columns = ["Epoch", "Loss", "Type"]

In [143]:
train_eval_loss_chart = alt.Chart(loss_df).mark_line().encode(
    x=alt.X('Epoch',title = 'Anzahl Epochen'),
    y=alt.Y('Loss', title='Mittlerer Fehler'),
    color=alt.Color('Type',title='Typ')
).properties(title='Fehlerentwicklung in Abhängigkeit von der Anzahl der Epochen')
train_eval_loss_chart

alt.Chart(...)

In [144]:
valid_accuracy_hist

{0: array(0., dtype=float32),
 1: array(0., dtype=float32),
 2: array(0., dtype=float32),
 3: array(0., dtype=float32),
 4: array(0., dtype=float32),
 5: array(0., dtype=float32),
 6: array(0., dtype=float32),
 7: array(0., dtype=float32),
 8: array(0., dtype=float32),
 9: array(0., dtype=float32),
 10: array(0., dtype=float32),
 11: array(0., dtype=float32),
 12: array(0., dtype=float32),
 13: array(0., dtype=float32),
 14: array(0., dtype=float32),
 15: array(0., dtype=float32),
 16: array(0., dtype=float32),
 17: array(0., dtype=float32),
 18: array(0.00083403, dtype=float32),
 19: array(0.00250209, dtype=float32),
 20: array(0.01084237, dtype=float32),
 21: array(0.03169308, dtype=float32),
 22: array(0.06255212, dtype=float32),
 23: array(0.09674729, dtype=float32),
 24: array(0.12260217, dtype=float32),
 25: array(0.13678065, dtype=float32),
 26: array(0.13928273, dtype=float32),
 27: array(0.13678065, dtype=float32),
 28: array(0.13177648, dtype=float32),
 29: array(0.13010843, 

In [145]:
train_accuracy_hist

{0: array([0.617181  , 0.82235193, 0.9916597 , 0.99916595, 0.99833196,
        0.84487075, 0.9616347 , 0.9266055 , 0.9791493 , 0.97164303,
        0.99249375, 0.84737283, 0.75062555, 0.9891576 , 0.9658048 ,
        0.85154295, 0.98999166,        nan, 0.96330273, 0.99916595,
        0.8932444 , 0.9874896 , 0.98665553, 0.9641368 ], dtype=float32),
 1: array(0., dtype=float32),
 2: array(0., dtype=float32),
 3: array(0., dtype=float32),
 4: array(0., dtype=float32),
 5: array(0., dtype=float32),
 6: array(0., dtype=float32),
 7: array(0., dtype=float32),
 8: array(0., dtype=float32),
 9: array(0., dtype=float32),
 10: array(0., dtype=float32),
 11: array(0., dtype=float32),
 12: array(0., dtype=float32),
 13: array(0., dtype=float32),
 14: array(0., dtype=float32),
 15: array(0., dtype=float32),
 16: array(0., dtype=float32),
 17: array(0., dtype=float32),
 18: array(0., dtype=float32),
 19: array(0.00083403, dtype=float32),
 20: array(0.00250209, dtype=float32),
 21: array(0.01084237, dt

In [146]:
# Erste Epoche löschen, da diese nicht neu initialisiert wird und Daten aus vorherigen Schritten enthält

del train_accuracy_hist[0]
del valid_accuracy_hist[0]

In [147]:
train_accuracy_df = pd.DataFrame.from_dict(train_accuracy_hist, orient = "index").reset_index()
train_accuracy_df["type"] = "train"
valid_accuracy_df = pd.DataFrame.from_dict(valid_accuracy_hist, orient = "index").reset_index()
valid_accuracy_df["type"] = "test"
accuracy_df = pd.concat([train_accuracy_df,valid_accuracy_df])
accuracy_df.columns = ["Epoch", "Accuracy", "Type"]

In [148]:
accuracy_df

Epoch  Accuracy   Type
0        1  0.000000  train
1        2  0.000000  train
2        3  0.000000  train
3        4  0.000000  train
4        5  0.000000  train
..     ...       ...    ...
144    145  0.292744   test
145    146  0.292744   test
146    147  0.292744   test
147    148  0.292744   test
148    149  0.292744   test

[298 rows x 3 columns]

In [149]:
train_eval_accuracy_chart = alt.Chart(accuracy_df).mark_line().encode(
 x=alt.X('Epoch', title='Anzahl der Epochen'),
 y=alt.Y('Accuracy', title='Genauigkeit'),
 color=alt.Color('Type',title='Typ')
).properties(title='Genauigkeiten des Trainings- und Testdatensatzes nach der Anzahl der Epochen')
train_eval_accuracy_chart

alt.Chart(...)